AllCops:
  Exclude:
    - '*.gemspec'
    - 'bin/**/*'
    - 'spec/dummy/**/*'
    - 'tmp/**/*'
    - 'bench/**/*'
    - 'lib/anycable/rpc/**/*'
    - 'Rakefile'
    - 'Gemfile'
    - 'db/schema.rb'
    - 'config/initializers/**/*'
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.4.1

Metrics/LineLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/FormatStringToken:
  Enabled: false
